### ISSUE TITLE
Bot Cicle

### ISSUE THREAD

**Issue by louysdev** [inti25/auto-pokemmo#2]
What is the cycle that the bot does when activating it? I have been carrying out several tests. The fishing and fighting part is excellent. But I think there is a problem (or I don't know how it works), the healing part in the pokemon center.

The character teleports to the pokemon center, but does not interact with the nurse. I was able to achieve healing by changing the a and b keys the other way around. But after healing the character it is still in the pokemon center.

(English via Google Translator)

**Comment by patangal** [comment]
For me it doesn’t even teleport to the pokecenter or heal even after it uses the leppaberries and and it’s pp

**Comment by inti25** [comment]
> For me it doesn’t even teleport to the pokecenter or heal even after it uses the leppaberries and and it’s pp

you have to open pp window in bottom left in game like that to detect low pp
![image](https://github.com/inti25/auto-pokemmo/assets/21986269/fc7ee170-a3bf-4cf0-bbc9-9ed5358000b5)

For leppaberries i will update later

**Comment by inti25** [comment]
> What is the cycle that the bot does when activating it? I have been carrying out several tests. The fishing and fighting part is excellent. But I think there is a problem (or I don't know how it works), the healing part in the pokemon center.
> 
> The character teleports to the pokemon center, but does not interact with the nurse. I was able to achieve healing by changing the a and b keys the other way around. But after healing the character it is still in the pokemon center.
> 
> (English via Google Translator)

what region have this issue ? for unova, if fixed it in latest verion.

**Comment by louysdev** [comment]
> > What is the cycle that the bot does when activating it? I have been carrying out several tests. The fishing and fighting part is excellent. But I think there is a problem (or I don't know how it works), the healing part in the pokemon center.
> > 
> > The character teleports to the pokemon center, but does not interact with the nurse. I was able to achieve healing by changing the a and b keys the other way around. But after healing the character it is still in the pokemon center.
> > 
> > (English via Google Translator)
> 
> what region have this issue ? for unova, if fixed it in latest verion.

I farm in unova.  Men, is it necessary to use the flight ocarina?. I use a Pokémon with flight.

There are times when you get stuck in the Pokémon center after 100 attempts.  Furthermore, low pp are not detected.  In my case it teleports when the Pokémon dies.

**Comment by inti25** [comment]
> > > What is the cycle that the bot does when activating it? I have been carrying out several tests. The fishing and fighting part is excellent. But I think there is a problem (or I don't know how it works), the healing part in the pokemon center.
> > > The character teleports to the pokemon center, but does not interact with the nurse. I was able to achieve healing by changing the a and b keys the other way around. But after healing the character it is still in the pokemon center.
> > > (English via Google Translator)
> > 
> > 
> > what region have this issue ? for unova, if fixed it in latest verion.
> 
> I farm in unova. Men, is it necessary to use the flight ocarina?. I use a Pokémon with flight.
> 
> There are times when you get stuck in the Pokémon center after 100 attempts. Furthermore, low pp are not detected. In my case it teleports when the Pokémon dies.

currently, teleport is default, i should modify scripts to use fly, (make sure hotkey set correctly: F4: Teleport Ocarina or Teleport move):

Low pp are not detected because missing pokemon moves window in bottom left, please refer:
https://github.com/inti25/auto-pokemmo/blob/main/gui_images/screen-setting.png
